Камень судьбы
htmlacademy-yii/555971-task-force-1 pull request #2
Opened 2019-11-09 18:06 UTC by maashey

2019-11-09 19:56 UTC, denis-khodakovskiy requested changes

2019-11-09 19:56 UTC, denis-khodakovskiy commented on Task.php
> +    private $tm_expire;
Имена свойств/функций/переменных и т.д. лучше не сокращать, а писать полностью, так код проще читать)

2019-11-09 19:56 UTC, denis-khodakovskiy commented on Task.php
> +    private static $statuses = [
Лучше оформить константой, как и список действий

2019-11-09 19:56 UTC, denis-khodakovskiy commented on Task.php
> +    public function __construct($owner_id, $status, $tm_expire=null, $doer_id=null)
В конструктор лучше передать ассоциативный массив где ключ - имя свойства, а значение, соответственно, значение свойства, а в самом конструкторе пробежать по всему массиву и сделать так - если свойство с именем текущего ключа есть в классе, то присвоить ему соответствующее значение, иначе ничего не делать. У РНР есть для этого функция `property_exists($className, $propertyName)`

2019-11-09 19:59 UTC, maashey commented on Task.php
> +    private $tm_expire;
спасибо, поправлю

2019-11-09 19:59 UTC, maashey commented on Task.php
> +    private static $statuses = [
ок

2019-11-09 19:59 UTC, maashey commented on Task.php
> +    public function __construct($owner_id, $status, $tm_expire=null, $doer_id=null)
ага, сделаю

2019-11-10 10:46 UTC, denis-khodakovskiy requested changes

2019-11-10 10:46 UTC, andrewverner commented on Task.php
> +
Тут лишние строки не нужны) После блока if - тоже

2019-11-10 10:46 UTC, andrewverner commented on Task.php
> +            if (property_exists(get_class($this), $name)) {
Тут вместо `get_class($this)` можно оставить просто `$this`

2019-11-10 10:46 UTC, andrewverner commented on Task.php
> +
Лишние пустые строки

2019-11-10 10:46 UTC, andrewverner commented on Task.php
> +
Лишние пустые строки

2019-11-10 10:46 UTC, andrewverner commented on Task.php
> +            throw new Exception('"' . $action. '" is not valid action for status "'. $this->status. '"');
Тут между знаками конкатенации пропущены пробелы. Конкатенацию лучше использовать как можно реже. РНР умеет интерполировать переменные в строку или есть функция sprintf:
`"'{$action} is not valid action for status '{$this->status}''";`
или `sprintf('"%s" is not valid action for status "%s"', $action, $this->status);`

2019-11-10 13:22 UTC, denis-khodakovskiy requested changes

2019-11-10 13:22 UTC, andrewverner commented on Task.php
> +        return in_array($this->status, $allStatuses);
Упрости до `return in_array($this->status, self::getAllStatuses());`. Так же с `isActionExist`

2019-11-10 13:22 UTC, andrewverner commented on Task.php
> +        if ($this->isStatusExist()) {
Старайся не использовать такие многоуровневые if-else блоки. Их в большинстве случаев можно декомпозировать на несколько независимых не вложенных, используя приём раннего возврата:

```
if (!$this->isStatusExist()) {
    throw new Exception("status `{$this->status}` not exist");
}

if (!$this->isActionExist($action)) {
    throw new Exception("action `{$action}` not exist");
}

if (!$this->isValidStatus($action)) {
    throw new Exception("`{$action}` is not valid action for status `{$this->status}`");
}

return self::NEXT_STATUSES[$action];
```

2019-11-10 14:52 UTC, merged